### ISSUE TITLE
D3-time-format Type expected

### ISSUE THREAD

**Issue by fpozzobon** [tomwanzek/d3-v4-definitelytyped#42]
Hi,

I get the following issue with d3-time-format/index.d.ts :
=> (53,63): error TS1110: Type expected.

Shouldn't it return "Date" instead of "(Date | null)" ?

Note : I use ts-loader

**Comment by tomwanzek** [comment]
In order to understand your issue, can you please clarify the following for me, assuming you have not made any changes to the definitions in your fork:

(1) Are you referring to an error caused on line the last line of this interface, i.e. the `utcParse(...)` method?

```
export interface TimeLocaleObject {
    format(specifier: string): (date: Date) => string;
    parse(specifier: string): (dateString: string) => (Date | null);
    utcFormat(specifier: string): (date: Date) => string;
    utcParse(specifier: string): (dateString: string) => (Date | null);
}
```

In the current file version in the repo this would be line 52.

(2) I am not using ts-loader, however, I suspect somewhere in the toolchain you are using, there might be an outdated version of the typescript compiler at play. I had seen similar postings  with TS1110 error elsewhere, when outdated compiler versions encounter intersection/union types.

The repo compiles without error as is, when using the typescript version in the `package.json` (currently 2.0.0). This specific file should also compile with 1.8.10 and 1.9.0-dev. So right now, I cannot replicate the error.

Ad 1) Assuming you are referring to the `utcParserFactory`, the parser function returned by the factory is written to return null, whenever a string cannot be parsed successfully with the given specifier string. So,  the `| null` is simply a cue as to the expected behavior of the parser in D3. I.e. it should not return `undefined` for a well-defined 'could not parse' failure mode.

**Comment by fpozzobon** [comment]
Thank you for your answer, in fact all the lines with (Date | null) have the error, I think this is because I am using the last stable version of typescript (1.8.10) and as far as I understand the Non-nullable types are introduced in the 2.0.0 (cf https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/).

The fork was simply a missclick ;)

**Comment by tomwanzek** [comment]
No worries. While the compilation context currently does not enforce strictNullChecks, you are right, the null and undefined types are also reaching into the new feature set. (Have been too focused on the `this` context to call it out).

As I finalize the definitions with completed tests for the definitions I am tracking under the Milestone Core Modules (Enhanced), I intent to create a derived set of backward (1.8.10) compatible definitions (tests). But I will need some guidance on the DefinitelyTyped side to facilitate the operation between the master branch definitions and those in the types-2.0 branch which feeds the @types organization. Separate story though... :wink:
